//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathDictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathDictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroundLoad {
            get {
                object obj = ResourceManager.GetObject("backgroundLoad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEdit_Cancel {
            get {
                object obj = ResourceManager.GetObject("btnEdit_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEdit_Cancel_1 {
            get {
                object obj = ResourceManager.GetObject("btnEdit_Cancel_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEdit_OK {
            get {
                object obj = ResourceManager.GetObject("btnEdit_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEdit_OK_1 {
            get {
                object obj = ResourceManager.GetObject("btnEdit_OK_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnGoBack {
            get {
                object obj = ResourceManager.GetObject("btnGoBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnGoForward {
            get {
                object obj = ResourceManager.GetObject("btnGoForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdAdd {
            get {
                object obj = ResourceManager.GetObject("cmdAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdDel {
            get {
                object obj = ResourceManager.GetObject("cmdDel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdEdit {
            get {
                object obj = ResourceManager.GetObject("cmdEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdFind {
            get {
                object obj = ResourceManager.GetObject("cmdFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdGroup_1 {
            get {
                object obj = ResourceManager.GetObject("cmdGroup_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cmdStartPage {
            get {
                object obj = ResourceManager.GetObject("cmdStartPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_Copy_1 {
            get {
                object obj = ResourceManager.GetObject("mnContext_Copy_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_Copy_2 {
            get {
                object obj = ResourceManager.GetObject("mnContext_Copy_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_CopySample_1 {
            get {
                object obj = ResourceManager.GetObject("mnContext_CopySample_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_CopySample_2 {
            get {
                object obj = ResourceManager.GetObject("mnContext_CopySample_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_CopySample_3 {
            get {
                object obj = ResourceManager.GetObject("mnContext_CopySample_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_Find {
            get {
                object obj = ResourceManager.GetObject("mnContext_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_Google_1 {
            get {
                object obj = ResourceManager.GetObject("mnContext_Google_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnContext_SelectAll_1 {
            get {
                object obj = ResourceManager.GetObject("mnContext_SelectAll_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_About_1 {
            get {
                object obj = ResourceManager.GetObject("mnHelp_About_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_CheckUpdate_2 {
            get {
                object obj = ResourceManager.GetObject("mnHelp_CheckUpdate_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_CheckUpdate_Database {
            get {
                object obj = ResourceManager.GetObject("mnHelp_CheckUpdate_Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_CheckUpdate_Version {
            get {
                object obj = ResourceManager.GetObject("mnHelp_CheckUpdate_Version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_Forum_3 {
            get {
                object obj = ResourceManager.GetObject("mnHelp_Forum_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_Forums_ToanHocVietNam {
            get {
                object obj = ResourceManager.GetObject("mnHelp_Forums_ToanHocVietNam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_Forums_ToanTin {
            get {
                object obj = ResourceManager.GetObject("mnHelp_Forums_ToanTin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_StartPage {
            get {
                object obj = ResourceManager.GetObject("mnHelp_StartPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_WatNew {
            get {
                object obj = ResourceManager.GetObject("mnHelp_WatNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnHelp_Website {
            get {
                object obj = ResourceManager.GetObject("mnHelp_Website", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Exit {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Export_1 {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Export_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Export_ModifiedByOwner_1 {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Export_ModifiedByOwner_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Export_ThisItem_2 {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Export_ThisItem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Import_1 {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Import_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Print {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnMenu_Save {
            get {
                object obj = ResourceManager.GetObject("mnMenu_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnTools_Addin {
            get {
                object obj = ResourceManager.GetObject("mnTools_Addin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnView_Language_2 {
            get {
                object obj = ResourceManager.GetObject("mnView_Language_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mnView_MaxView {
            get {
                object obj = ResourceManager.GetObject("mnView_MaxView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictureBox1 {
            get {
                object obj = ResourceManager.GetObject("pictureBox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
